"use client";

import React from "react";
import { Shield, EyeOff, Mountain, Building, Radio, CheckCircle } from "lucide-react";

export function DefenseScenarios() {
  const scenarios = [
    {
      title: "LoC Sub-Surface Tunnel Interdiction",
      subtitle: "Anti-Tunneling Detection in Vulnerable Border Sectors",
      tag: "STRATEGIC PRIORITY",
      icon: EyeOff,
      color: "text-red-400",
      border: "border-red-500/30",
      bg: "bg-red-950/10",
      challenge:
        "Adversaries exploit alluvial soil along the International Border and LoC (e.g. Samba, Kathua corridors) to dig covert tunnels 15 to 30 feet underground, bypassing physical border fencing completely undetected by surface optical and thermal sensors.",
      solution:
        "BHOOMI ground stakes capture low-frequency seismic compression waves generated by pickaxe striking, manual shoveling, and rotary drilling up to 15 meters below ground, sending pinpoint geographic alert vectors to border posts.",
      impact: [
        "Detects digging activity before tunnel crosses the zero line",
        "Operates continuously 24/7/365 without human fatigue",
        "Zero detectable RF emission prevents adversary from locating sensor line",
      ],
    },
    {
      title: "Zero-Visibility Infiltration Defense",
      subtitle: "Fog, Monsoon Rains & Dense Forest Canopy",
      tag: "TACTICAL EXCELLENCE",
      icon: Mountain,
      color: "text-cyan-400",
      border: "border-cyan-500/30",
      bg: "bg-cyan-950/10",
      challenge:
        "Covert infiltrators deliberately time border crossings during dense winter fog (Paharpur / Punjab stretches) or monsoon cloudbursts when thermal imagers suffer thermal washout and optical cameras have near-zero visibility.",
      solution:
        "Seismic ground coupling is unaffected by fog, rain, or forest canopy. When an infiltrator traverses the terrain, characteristic rhythmic footfall micro-vibrations are captured and cross-verified against acoustic rustle.",
      impact: [
        "Immune to atmospheric obscuration, fog, smoke, and downpours",
        "Functions flawlessly through dense rhododendron and pine canopies",
        "Edge AI filters out torrential rainfall noise using wavelet transforms",
      ],
    },
    {
      title: "Forward Operating Base & Depot Perimeter",
      subtitle: "Critical Military Infrastructure Protection",
      tag: "PERIMETER SHIELD",
      icon: Building,
      color: "text-emerald-400",
      border: "border-emerald-500/30",
      bg: "bg-emerald-950/10",
      challenge:
        "Isolated ammunition depots, radar stations, and Forward Operating Bases (FOBs) in counter-insurgency zones face sudden stand-off attacks or perimeter fence breach attempts by armed squads.",
      solution:
        "A multi-layered ring of BHOOMI nodes staked 100–300 meters outside the perimeter wall provides early warning before intruders reach direct weapons range, alerting quick reaction teams automatically.",
      impact: [
        "Provides 3 to 5 minutes of early reaction time for QRF teams",
        "Self-powered nodes require zero perimeter trenching or cable laying",
        "Can be rapidly deployed or repositioned in dynamic combat situations",
      ],
    },
    {
      title: "LAC High-Altitude Mountain Passes",
      subtitle: "Rugged Trans-Himalayan Ingress Monitoring",
      tag: "EXTREME TERRAIN",
      icon: Shield,
      color: "text-amber-400",
      border: "border-amber-500/30",
      bg: "bg-amber-950/10",
      challenge:
        "Steep mountainous passes (14,000+ ft) along the Line of Actual Control experience sub-zero temperatures (-20°C), rocky scree, and zero civilian power or cellular infrastructure.",
      solution:
        "BHOOMI ground stakes with acoustic impedance matched tips anchor into rocky scree. Solar harvesting panels recharge LiFePO4 batteries during thin-atmosphere sunlight, maintaining persistent autonomous mesh relays.",
      impact: [
        "Tested for extreme temperature operation from -20°C to +60°C",
        "14+ days autonomous battery buffer for prolonged blizzard conditions",
        "LoRa mesh spans mountain ravines without requiring line-of-sight cables",
      ],
    },
  ];

  return (
    <div className="space-y-8">
      {scenarios.map((item, idx) => {
        const Icon = item.icon;
        return (
          <div
            key={idx}
            className={`p-6 sm:p-8 rounded-2xl border ${item.border} ${item.bg} bg-[#090d16] shadow-xl hover:border-emerald-500/40 transition-all`}
          >
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-5 border-b border-slate-800">
              <div className="flex items-center gap-3">
                <div className={`p-2.5 rounded-xl bg-slate-900 border border-slate-800 ${item.color}`}>
                  <Icon className="w-6 h-6" />
                </div>
                <div>
                  <span className={`text-[10px] font-mono font-bold uppercase tracking-wider ${item.color}`}>
                    {item.tag}
                  </span>
                  <h3 className="text-xl font-bold text-white tracking-tight">
                    {item.title}
                  </h3>
                  <span className="text-xs text-slate-400 block mt-0.5 font-mono">
                    {item.subtitle}
                  </span>
                </div>
              </div>
              <span className="text-[11px] font-mono text-slate-500 bg-slate-900 px-3 py-1 rounded-lg border border-slate-800 self-start sm:self-auto">
                OPERATIONAL SCENARIO 0{idx + 1}
              </span>
            </div>

            <div className="mt-6 grid grid-cols-1 lg:grid-cols-12 gap-6">
              <div className="lg:col-span-6 space-y-4">
                <div>
                  <span className="text-[11px] font-mono text-red-400 uppercase font-bold block mb-1">
                    CURRENT OPERATIONAL GAP:
                  </span>
                  <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
                    {item.challenge}
                  </p>
                </div>
                <div>
                  <span className="text-[11px] font-mono text-emerald-400 uppercase font-bold block mb-1">
                    BHOOMI TACTICAL SOLUTION:
                  </span>
                  <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
                    {item.solution}
                  </p>
                </div>
              </div>

              <div className="lg:col-span-6 bg-slate-950/80 p-5 rounded-xl border border-slate-800/80 space-y-3">
                <span className="text-[11px] font-mono text-slate-400 uppercase font-semibold block">
                  TACTICAL ADVANTAGES FOR FORWARD FORCES:
                </span>
                <ul className="space-y-2.5">
                  {item.impact.map((impact, i) => (
                    <li key={i} className="flex items-start gap-2.5 text-xs text-slate-300">
                      <CheckCircle className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                      <span>{impact}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        );
      })}
    </div>
  );
}
