"use client";

import React from "react";
import { Shield, EyeOff, Mountain, Building, Radio, CheckCircle, Plane } from "lucide-react";

export function DefenseScenarios() {
  const scenarios = [
    {
      title: "LoC Sub-Surface Tunnel Interdiction",
      subtitle: "Anti-Tunneling Detection & Automated Aerial Thermal Verification",
      tag: "STRATEGIC PRIORITY",
      icon: EyeOff,
      color: "text-red-400",
      border: "border-red-500/30",
      bg: "bg-red-950/10",
      challenge:
        "Adversaries exploit alluvial soil along the International Border and LoC (e.g. Samba, Kathua corridors) to dig covert tunnels 5 to 15 meters underground, bypassing physical border fencing completely undetected by surface optical and thermal sensors.",
      solution:
        "BHOOMI ground stakes capture low-frequency P/S seismic compression waves generated by pickaxes, shoveling, and drilling up to 15 meters below ground. Once classified, the Sector Gateway commands the nearest autonomous drone to launch in <15 seconds to the exact TDOA coordinates, utilizing its FLIR Boson 640 thermal camera to pinpoint excavation spoil heaps and ventilation shafts.",
      droneAction:
        "Autonomous Cued UAV Flight: Retracts dock lid in <3s, reaches TDOA coordinates in 24 seconds, establishes thermal video lock on tunnel shaft entrance.",
      impact: [
        "Detects digging activity before tunnel crosses the zero line",
        "Autonomous drone visually confirms surface excavation mounds within 30 seconds",
        "Zero detectable RF emission prevents adversary from locating sensor line",
      ],
    },
    {
      title: "Zero-Visibility Infiltration Defense",
      subtitle: "Dense Winter Fog, Monsoon Downpours & Forest Canopy",
      tag: "TACTICAL EXCELLENCE",
      icon: Mountain,
      color: "text-cyan-400",
      border: "border-cyan-500/30",
      bg: "bg-cyan-950/10",
      challenge:
        "Covert infiltrators deliberately time border crossings during dense winter fog (Paharpur / Punjab stretches) or monsoon cloudbursts when thermal imagers suffer thermal washout and optical cameras have near-zero visibility.",
      solution:
        "Seismic ground coupling is completely immune to weather conditions. The moment an intruder sets foot on soil, seismic Rayleigh waves are cross-verified with acoustic harmonics. The autonomous VTOL drone launches from its heated dock and loiters at 50m AGL, using FLIR Boson 640 long-wave infrared to track human body heat blooms (37°C) through fog and tree canopy.",
      droneAction:
        "All-Weather Aerial Intercept: Drone climbs above low-level fog layer, tracking hostile cadence and feeding real-time target vectors to QRF.",
      impact: [
        "100% detection rate during heavy fog, dense smoke, and torrential rain",
        "Autonomous drone delivers bird's-eye thermal confirmation without exposing patrol squads to ambushes",
        "Wavelet denoising filters out torrential monsoonal noise locally",
      ],
    },
    {
      title: "Forward Operating Base & Depot Perimeter",
      subtitle: "Critical Military Infrastructure Shield & QRF Cueing",
      tag: "PERIMETER SHIELD",
      icon: Building,
      color: "text-emerald-400",
      border: "border-emerald-500/30",
      bg: "bg-emerald-950/10",
      challenge:
        "Isolated ammunition depots, radar stations, and Forward Operating Bases (FOBs) in counter-insurgency zones face sudden stand-off attacks or perimeter fence breach attempts by armed squads.",
      solution:
        "A multi-layered ring of BHOOMI nodes staked 100–300 meters outside the perimeter wall provides early seismic warning before intruders reach direct weapons range. The nearest docked drone automatically launches in <15 seconds, circling the breach coordinates with thermal tracking and providing 3 to 5 minutes of visual warning for Quick Reaction Force (QRF) mobilization.",
      droneAction:
        "Rapid Intercept & Illumination: Drone provides continuous 35-minute aerial thermal surveillance over perimeter approach avenues.",
      impact: [
        "Provides 3 to 5 minutes of advance visual reaction time for base defence forces",
        "Self-powered nodes require zero perimeter trenching or vulnerable line cabling",
        "Can be rapidly redeployed to forward patrol bases in dynamic combat theaters",
      ],
    },
    {
      title: "LAC High-Altitude Mountain Passes",
      subtitle: "Rugged Trans-Himalayan Ingress Monitoring & Airborne Mesh Relay",
      tag: "EXTREME TERRAIN",
      icon: Shield,
      color: "text-amber-400",
      border: "border-amber-500/30",
      bg: "bg-amber-950/10",
      challenge:
        "Steep mountainous passes (14,000+ ft) along the Line of Actual Control experience sub-zero temperatures (-40°C), rocky scree, and zero civilian power or cellular infrastructure.",
      solution:
        "BHOOMI ground stakes anchor directly into rocky scree with acoustic impedance matching. Climate-controlled drone docks with heated tracks and Qi wireless charging withstand Siachen blizzards. When dispatched, the VTOL drone carries an onboard LoRa repeater, bridging blind mountain ravines and streaming aerial recon back to Battalion HQ.",
      droneAction:
        "High-Altitude Aerial Recon & Relay: Operates up to 4,500m ASL, bridging mountainous RF dead zones while inspecting high-altitude saddles.",
      impact: [
        "MIL-STD-810H tested for extreme temperatures from -40°C to +70°C",
        "7+ days autonomous battery buffer for prolonged Himalayan blizzard conditions",
        "Airborne LoRa repeater bridges deep mountain defiles without cabling",
      ],
    },
  ];

  return (
    <div className="space-y-8">
      {scenarios.map((item, idx) => {
        const Icon = item.icon;
        return (
          <div
            key={idx}
            className={`p-6 sm:p-8 rounded-2xl border ${item.border} ${item.bg} bg-[#090d16] shadow-xl hover:border-emerald-500/40 transition-all`}
          >
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-5 border-b border-slate-800">
              <div className="flex items-center gap-3">
                <div className={`p-2.5 rounded-xl bg-slate-900 border border-slate-800 ${item.color}`}>
                  <Icon className="w-6 h-6" />
                </div>
                <div>
                  <span className={`text-[10px] font-mono font-bold uppercase tracking-wider ${item.color}`}>
                    {item.tag}
                  </span>
                  <h3 className="text-xl font-bold text-white tracking-tight">
                    {item.title}
                  </h3>
                  <span className="text-xs text-slate-400 block mt-0.5 font-mono">
                    {item.subtitle}
                  </span>
                </div>
              </div>
              <span className="text-[11px] font-mono text-slate-500 bg-slate-900 px-3 py-1 rounded-lg border border-slate-800 self-start sm:self-auto font-bold">
                SCENARIO 0{idx + 1}
              </span>
            </div>

            <div className="mt-6 grid grid-cols-1 lg:grid-cols-12 gap-6">
              <div className="lg:col-span-6 space-y-4">
                <div>
                  <span className="text-[11px] font-mono text-red-400 uppercase font-bold block mb-1">
                    CURRENT OPERATIONAL GAP:
                  </span>
                  <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
                    {item.challenge}
                  </p>
                </div>
                <div>
                  <span className="text-[11px] font-mono text-emerald-400 uppercase font-bold block mb-1">
                    BHOOMI TRI-DOMAIN SOLUTION:
                  </span>
                  <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
                    {item.solution}
                  </p>
                </div>

                <div className="p-3 rounded-xl bg-slate-950 border border-amber-500/30 flex items-start gap-2.5">
                  <Plane className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
                  <div>
                    <span className="text-[10px] font-mono text-amber-300 font-bold block">
                      AUTONOMOUS AERIAL DRONE RESPONSE:
                    </span>
                    <span className="text-xs text-slate-300 font-sans">{item.droneAction}</span>
                  </div>
                </div>
              </div>

              <div className="lg:col-span-6 bg-slate-950/80 p-5 rounded-xl border border-slate-800/80 space-y-3">
                <span className="text-[11px] font-mono text-slate-400 uppercase font-semibold block">
                  TACTICAL ADVANTAGES FOR FORWARD COMMAND:
                </span>
                <ul className="space-y-2.5">
                  {item.impact.map((impact, i) => (
                    <li key={i} className="flex items-start gap-2.5 text-xs text-slate-300">
                      <CheckCircle className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                      <span>{impact}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        );
      })}
    </div>
  );
}
